Update HX8357 driver to 8.x/9.x transitional code
adafruit/Adafruit_CircuitPython_HX8357 pull request #23
Opened 2024-03-24 00:02 UTC by DJDevon3

3.5" TFT Featherwing display driver needs updating for 9.0.  Added 8.x to 9.x transitional code so it should work in either 8.x or 9.x  Only tested in 9.x, needs 8.x testing.  In 9.x the previous driver commit would bring up future warnings.

```
FutureWarning: Display moved from displayio to busdisplay
FutureWarning: Display renamed BusDisplay
```
These are now addressed with this commit and no warnings are present in 9.0

2024-03-24 21:13 UTC, tekktrik commented on adafruit_hx8357.py
> +    def __init__(self, bus: FourWire.FourWire, **kwargs) -> None:
The type annotation now just be `FourWire`, but this is great, thanks!

2024-03-24 21:13 UTC, tekktrik requested changes
One small change, but otherwise, this is great!  Good find and fix.

2024-03-25 01:28 UTC, DJDevon3 commented
Thanks!  Also got Github Desktop sorted out so now it's submitting all line endings in LF format only.  No more thousands of pylint line ending errors.

2024-03-25 13:43 UTC, tekktrik approved these changes
This looks great, thank you!

2024-03-25 13:43 UTC, merged